openapi: 3.0.0
info:
  title: Todo App API
  description: API for the Todo application backend that the frontend will connect to
  version: 1.0.0

paths:
  /tasks:
    get:
      summary: Get all tasks
      description: Retrieve a list of all tasks with optional filtering and sorting
      parameters:
        - name: completed
          in: query
          description: Filter tasks by completion status
          required: false
          schema:
            type: boolean
        - name: priority
          in: query
          description: Filter tasks by priority level
          required: false
          schema:
            type: string
            enum: [low, medium, high]
        - name: tag
          in: query
          description: Filter tasks by tag
          required: false
          schema:
            type: string
        - name: sort
          in: query
          description: Sort field (created_at, priority, due_date, completed)
          required: false
          schema:
            type: string
        - name: reverse
          in: query
          description: Reverse sort order
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'

    post:
      summary: Create a new task
      description: Add a new task to the todo list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  description: Task title
                description:
                  type: string
                  description: Task description
                priority:
                  type: string
                  enum: [low, medium, high]
                  default: medium
                tags:
                  type: array
                  items:
                    type: string
                due_date:
                  type: string
                  format: date
                  description: Due date in YYYY-MM-DD format
                recurrence:
                  type: string
                  enum: [daily, weekly]
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input

  /tasks/{id}:
    get:
      summary: Get a specific task
      description: Retrieve a single task by ID
      parameters:
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    $ref: '#/components/schemas/Task'
        '404':
          description: Task not found

    put:
      summary: Update a task
      description: Update an existing task
      parameters:
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                completed:
                  type: boolean
                priority:
                  type: string
                  enum: [low, medium, high]
                tags:
                  type: array
                  items:
                    type: string
                due_date:
                  type: string
                  format: date
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    $ref: '#/components/schemas/Task'
        '404':
          description: Task not found

    delete:
      summary: Delete a task
      description: Remove a task from the todo list
      parameters:
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
      responses:
        '200':
          description: Task deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '404':
          description: Task not found

components:
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - created_at
      properties:
        id:
          type: string
          description: Unique identifier for the task
        title:
          type: string
          description: Task title
        description:
          type: string
          description: Task description
        completed:
          type: boolean
          description: Completion status
          default: false
        priority:
          type: string
          enum: [low, medium, high]
          description: Priority level
          default: medium
        tags:
          type: array
          items:
            type: string
          description: Tags associated with the task
        due_date:
          type: string
          format: date
          description: Due date in YYYY-MM-DD format
        recurrence:
          type: string
          enum: [daily, weekly]
          description: Recurrence pattern
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp