# Default values for todo-frontend
replicaCount: 2

image:
  repository: todo-frontend
  pullPolicy: IfNotPresent
  tag: "v1.0.1"

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi