name: Deploy Backend to Hugging Face

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Docker login using PAT
      - name: Login to Hugging Face (Docker)
        run: |
          echo ${{ secrets.HF_TOKEN }} | docker login -u ${{ secrets.HF_USERNAME }} --password-stdin

      - name: Build backend image
        run: |
          docker build -t todo-backend ./backend

      - name: Tag image
        run: |
          docker tag todo-backend hf.co/spaces/iqra-khan-2998/full_stack_todo:latest

      - name: Push image
        run: |
          docker push hf.co/spaces/iqra-khan-2998/full_stack_todo:latest
